config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'
  get 'tasks/create'
  get 'tasks/select_date'
  get 'tasks/user_weight', :as => "user_weight"
  get 'tasks/select_user', :as => "select_user"
  get 'task/event' => "tasks#event", :as => "event"
  post 'task/comments/create' => "comments#create"
  post 'task/attachments/create' => "attachments#create"
  get 'attachments/show',  :as => "download"

  match "tasks/participate" => "tasks#participate", :via => :post
  match "tasks/create_date" => "tasks#create_date", :via => :patch, :as => "create_date"
  get "tasks/delete_date/:task_id" => "tasks#delete_date", :as => "delete_date"
  match "tasks/create_user_weight" => "tasks#create_user_weight", :via => :patch, :as => "create_user_weight"

  resources :tasks, :except => :show

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "account" => "sessions#account", :as => "account"
  get "help" => "welcome#show", :as => "help"

  get "addfriends" => "friendships#new", :as => "addfriends"

  resources :users do
    collection do
      post 'multiple_update'
    end
  end

  resources :sessions
  resources :friendships
  resources :responses

  root 'welcome#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :attendees
  has_many :users, :through => :attendees
  has_many :selectdates, dependent: :destroy
  has_many :attachments
  has_many :comments



  validates :title, presence: true,
            length: { minimum: 1 },
            length: { maximum: 18 }

  validates :text, presence: true,
            length: { minimum: 1 }

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  #create a new event
  def create
    @task = Task.new(task_params)
    if @task.save
      #flash[:success] = "Great! Your task has been created!"
      redirect_to :action => 'select_date', :id => @task
    else
      render 'new'
    end
  end

  #destroy a given event
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "Removed event"
    redirect_to account_path
  end

  #show all events
  def show
    @task = Task.find(params[:id])
  end

  #show select dates page
  def select_date
    @task = Task.find(params[:id])
    @taskdates = Selectdate.where(task_id: params[:id])
  end

  #add dates to a given event
  def create_date
    @task = Task.find(params[:id])
    #@task.update_attributes!(meeting_date: params[:tasks][:meeting_date], meeting_start_time: params[:tasks][:started_at], meeting_end_time: params[:tasks][:ended_at])
    #@taskdates = @task.selectdates.create(task_date: params[:tasks][:meeting_date])
    @taskdates = @task.selectdates.create()
    date = params[:tasks][:meeting_date] + " "
    time = params[:tasks][:meeting_time]
    datetime = date << time
    @taskdates.update_attributes!(task_date: datetime)

    redirect_to :action => 'select_date', :id => @task

  end

  #delete dates from a given event
  def delete_date
    @task = Task.find(params[:task_id])
    @date = Selectdate.where(id: params[:date_id]).first
    @date.destroy
    flash[:notice] = "Date removed"
    redirect_to :action => 'select_date', :id => @task
  end

  #show the select participant page
  def select_user
    @task = Task.find(params[:id])
    if @task.selectdates.length < 2
      flash[:notice] = "Please choose at least two dates"
      redirect_to :action => 'select_date', :id => @task
    end
  end

  #add users to the event
  def participate
    @task = Task.find(params[:id])
    @task.users << User.all

    @attendees = Attendee.where(User_id: params[:user_checkbox])
    Attendee.transaction do
      @attendees.each do |attendee|
        attendee.update_attributes!(participate: true)
      end
    end

    redirect_to :action => 'user_weight', :id => @task
  end


  #show the select user weight page
  def user_weight
    @task = Task.find(params[:id])
    users = @task.attendees.where(participate: true)
    if users.length < 2
      flash[:notice] = "Please choose at least two participants"
      redirect_to :action => 'select_user', :id => @task
    end
    @participants = Attendee.where(participate: true, task_id: params[:id])
  end

  #add user weights to participants
  def create_user_weight
    @participant = Attendee.where(participate: true, task_id: params[:id])
  end


  #show the event overview page
  def event
    @task = Task.where(id: params[:id])
    @dates = Selectdate.where(task_id: params[:id]).order('task_date')
    @comments = Comment.where(task_id: params[:id])
    @attachments = Attachment.where(task_id: params[:id])
    p @attachments
    @participants = Attendee.where(participate: true, task_id: params[:id])
    @users = @participants.map { |p| User.find_by id: p.user_id }.to_set.to_a
    score = Hash.new
    @dates.each do |date|
      score.merge!("#{date.id}" => 0)
    end
    @dates.each do |date|
      responses = Response.where(selectdate_id: date.id)
      responses.each do |response|
        weight = Attendee.where(user_id: response.user_id, task_id: params[:id]).first.user_weight
        score["#{date.id}"] += weight
      end
    end
    score = score.sort_by{ |k, v| v }.reverse
    @suggestion = score
  end


  private
    def task_params
      params.require(:task).permit(:title, :text, :user_id)
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/event.html.erb
<div id="event-view" class="view">

        <div class="event-info floatleft">
            <h2><%= @task.first.title %></h2>
            <div class="event-description">
                <%= @task.first.text %>
            </div>
            <div class="suggested-dates">
                <h2>Suggested Dates</h2>
                    <div class="event-date date-suggestion">
                        <div class="month floatleft">
                            <%= Selectdate.where(id: @suggestion.first.first.to_i).first.task_date.strftime("%B") %>
                        </div>
                        <div class="year floatright">
                            <%= Selectdate.where(id: @suggestion.first.first.to_i).first.task_date.strftime("%Y") %>
                        </div>
                        <div class="day">
                            <%= Selectdate.where(id: @suggestion.first.first.to_i).first.task_date.strftime("%d") %>
                        </div>
                        <div class="time">
                            <%= Selectdate.where(id: @suggestion.first.first.to_i).first.task_date.strftime("%H:%M") %>
                        </div>
                        <div class="score">
                            Score: <%= @suggestion.first.second %>
                        </div>
                    </div>
                <div class="runnerups">
                    <% for i in 1..@suggestion.length - 1 do %>
                        <div class="runnerup">
                            <%= Selectdate.where(id: @suggestion[i].first.to_i).first.task_date.strftime("%d.%m.%y %H:%M") %>
                            <span>Score: <%= @suggestion[i].second %></span>
                        </div>
                    <% end %>
                </div>
            </div>
            <div id="fileupload">
                <%= form_for :attachment, :url => "attachments/create", :multipart => true do |f| %>
                    <%= f.file_field 'attachment' %>
                    <div id="submit-attachment" class="button buttonshadow">
                        <%= f.submit "upload" %>
                    </div>
                    <%= f.text_field :task_id, :class => "id_hide", :value => @task.first.id %>
                <% end %>
            </div>
        </div>

        <div class="event-dates floatright">
            <% for date in @dates do %>
                <div class="event-date floatleft">
                    <div class="month floatleft">
                        <%= date.task_date.strftime("%B") %>
                    </div>
                    <div class="year floatright">
                        <%= date.task_date.strftime("%Y") %>
                    </div>
                    <div class="day">
                        <%= date.task_date.strftime("%d") %>
                    </div>
                    <div class="time">
                        <%= date.task_date.strftime("%H:%M") %>
                    </div>
                </div>
            <% end %>
        </div>

        <div class="participants floatright">
            <h2>Participants</h2>
            <% for participant in @participants do %>
                <%= link_to (participant.user), :controller => 'user', :action => :show, :id => participant.user.id do %>
                    <div class="participant floatleft">
                        <div class="avatar_small floatleft">
                            <%= image_tag avatar_url(participant.user, 50), :class => "avatar" %>
                        </div>
                        <div class="fname floatleft">
                            <%= participant.user.username %>
                        </div>
                        <div class="fcompany floatleft">
                            <%= participant.user.company %>
                        </div>
                        <% if participant.answered != nil %>
                            <i class="fa fa-check"> answered</i>
                        <% end %>
                    </div>
                <% end %>
            <% end %>
        </div>

        <div class="event-comments floatright">
            <a id="showcomments" class="btn-show floatright">show</a>
            <h2>Comments</h2>
            <div id="comments">
                <% if @comments.length == 0 %>
                    <span>No comments</span>
                <% end %>
                <% for comment in @comments do %>
                    <div class="comment">
                        <div class="cmt-user floatleft">
                            <%= comment.username %>
                        </div>
                        <div class="cmt-text floatright">
                            <%= comment.text %>
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="inputform">
                <%= form_for :comment, :url => "comments/create" do |f| %>
                    <%= f.text_field :username, :class => "id_hide", :value => current_user.username %>
                    <%= f.text_field :task_id, :class => "id_hide", :value => @task.first.id %>
                        <%= f.text_area :text%>
                        <%= f.submit "send", class: "buttoninput buttonshadow floatright btn-comment" %>
                <% end %>
            </div>
        </div>

        <div class="event-attachments floatright">
            <a id="showattachments" class="btn-show floatright">show</a>
            <h2>Attachments</h2>
            <div id="attachments">
                <% if @attachments.length == 0 %>
                    <span>No attachments</span>
                <% end %>
                <% for attachment in @attachments do %>
                    <div class="attachment">
                        <div class="filename floatleft">
                            <%= attachment.filename %>
                        </div>
                        <div class="btn-download floatright">
                            <%= link_to download_path(a_id: attachment.id) do %>
                                <i class="fa fa-cloud-download"></i>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
</div>

app/views/tasks/new.html.erb
<div id="createNoodle" class="view">

  <h2>Create Noodle</h2>

  <div class="inputform">
    <%= form_for :task, url: tasks_path do |f| %>

        <% if @task.errors.any? %>
            <div class="error_messages">
              <% for message in @task.errors.full_messages %>
                <p><%= message %></p>
              <% end %>
            </div>
        <% end %>



        <p>
          <%= f.text_field :title, :placeholder => "Title" %>
        </p>

        <p>
          <%= f.text_area :text, :placeholder => "Description" %>
        </p>
        <p>
          <%= f.text_field :user_id, :class => "id_hide", :value => current_user.id %>
        </p>
        <p>
          <%= f.submit "Create", :class => "buttoninput buttonshadow"%>
        </p>
    <% end %>
  </div>
</div>

app/views/tasks/select_date.html.erb
<div class="view">
  <h2 id="select_date_title">Select dates</h2>

  <div class="flashmsg">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  </div>

  <% @taskdates.each do |date| %>
    <div class="dates">
      <p><%= date.task_date.strftime("%A, %d %B %Y %H:%M") %></p>
      <%= link_to delete_date_path(:date_id => date.id, :task_id => @task.id) do %>
        <i class="fa fa-times"></i>
      <% end %>
    </div>
  <% end %>

  <div class="inputform" id="select_date_form">
    <%= form_for @task, :url => {action: "create_date"} do |f| %>

          <%= text_field("tasks", "meeting_date", placeholder: "dd-mm-yyyy", id: "datepicker") %>

          <%= text_field("tasks", "meeting_time", placeholder: "hh:mm", id: "timepicker") %>

        <p>
          <%= hidden_field_tag :id, @task.id %>
          <%= f.submit "Add Date", :class => "buttoninput buttonshadow" %>
        </p>
    <% end %>
  </div>
  <%= link_to "Continue", select_user_path(:id => @task), :class => "button buttonshadow" %>
</div>

app/views/tasks/select_user.html.erb
<div class="view">
    <h2>Select Users</h2>

    <div class="flashmsg">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
    </div>
    
    <div class="inputform" id="select-user-form">
        <%= form_tag("/tasks/participate/", :method => "post", :id => @task) do %>

              <% for friendship in current_user.friendships %>
                <% if friendship.friend %>
                    <div class="checkfriend">
                        <div class="checkbox floatleft">
                            <%= check_box_tag  "user_checkbox[]", friendship.friend.id %> 
                        </div>
                        <div class="checkname">
                            <%= friendship.friend.username %>
                        </div>
                    </div>
                <% end %>
              <% end %>
            <%= hidden_field_tag :id, @task.id %>
            <%= submit_tag("Add", :class => "buttonshadow buttoninput select_button") %>
        <% end %>
    </div>
</div>

app/views/tasks/user_weight.html.erb
<div class="view">
    <h2>Select the Weight</h2>
    <div class="inputform">
        <%= form_tag multiple_update_users_path do %>
              <% @participants.each do |part| %>
                <div class="userweight">
                    <div class="checkname floatleft">
                        <%= part.user.username %>
                    </div>
                    <div class="select_weight floatright">
                        <%= select_tag "users[#{part.user.id}][user_weight]", options_for_select([['very low', 1], ['low', 2], ['medium', 3], ['high', 4], ['very high', 5]], part.user_weight) %>
                    </div>
                </div>
              <% end %>
            <%= hidden_field_tag :id, @task.id %>
            <%= submit_tag "Update", :class => "buttoninput buttonshadow select_button" %>
        <% end %>
    </div>
</div>