config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'
  get 'tasks/create'
  get 'tasks/select_date'
  get 'tasks/user_weight', :as => "user_weight"
  get 'tasks/select_user', :as => "select_user"
  get 'task/event' => "tasks#event", :as => "event"
  post 'task/comments/create' => "comments#create"
  post 'task/attachments/create' => "attachments#create"
  get 'attachments/show',  :as => "download"

  match "tasks/participate" => "tasks#participate", :via => :post
  match "tasks/create_date" => "tasks#create_date", :via => :patch, :as => "create_date"
  get "tasks/delete_date/:task_id" => "tasks#delete_date", :as => "delete_date"
  match "tasks/create_user_weight" => "tasks#create_user_weight", :via => :patch, :as => "create_user_weight"

  resources :tasks, :except => :show

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "account" => "sessions#account", :as => "account"
  get "help" => "welcome#show", :as => "help"

  get "addfriends" => "friendships#new", :as => "addfriends"

  resources :users do
    collection do
      post 'multiple_update'
    end
  end

  resources :sessions
  resources :friendships
  resources :responses

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  #show help page
  def show
    render 'help'
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/help.html.erb
<div class="view" id="helppage">
    <h2>Help</h2>
    <h3>What is Noodle</h3>

    <p>Noodle is a web application for smart scheduling. Manage your meetings and appointments with your business team, your family and with your best friends in a fast, simple and appropriate way.</p>

    <h3>Why you should use Noodle</h3>

    <p>Noodle is more than just doodle. Manage your meetings with breathtaking features. Create an account and invite your friends to participate at your individual scheduling adventure. We know it better than all, that today it is literally an adventure to set an appropriate date for a necessary meeting. Often not all concerned people can participate. But do you really need to have all your invited members present on a meeting? With Noodle you can easily allocate weighted preferences to each meeting member. Who is more important to be present at the meeting than others? Who should absolutely be at the concerned meeting and who not?! Let this question comfortably be solved by Noodle, that will schedule the perfect date for you with a high precision dependent on your personal set weighted preferences. You will see, that scheduling has never been so easy. Your Meetings will be successful, once the important meeting members are present.</p>

    <h3>How to use Noodle</h3>
    <ol>
        <li>Create an Account</li>
        <li>Create an event</li>
        <li>Select a date and the appropriate time</li>
        <li>Select your friends</li>
        <li>Allocate weighted preferences to all member - very low, low, medium, high, very high</li>
        <li>Let Noodle choose the right date for you</li>
    </ol>
</div>

app/views/welcome/index.html.erb
<% if current_user %>
    <div class="flashmsg">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
    </div>
<% end %>

<% if not current_user %>
    <h1 id="welcome">Welcome to the Noodle Project</h1>
<% end %>

<div id="penlong">
    <%= link_to new_task_path do%>
        <%= image_tag("penlong.png",  height: 500) %>
    <% end %>
</div>

<div class="floatright" id="introtext">
    <p>Start your scheduling adventure here with Noodle - find the appropriate date thanks to Noodle’s smart scheduling algorithm. Organizing successful meetings without all required members? </p>

    <p>Let Noodle be your scheduling master that selects not only a simple date - but the best one for YOU and your needs.  </p>

    <% if not current_user %>
        <%= link_to signup_path do %>    
            <div class="buttonhome floatleft buttonshadow" id="signupbutton">
                Sign up
            </div>
        <% end %>
        
        <%= link_to login_path do%>
            <div class="buttonhome floatleft buttonshadow" id="loginbutton">
                Login
            </div>
        <% end %>
    <% else %>
        <%= link_to new_task_path do%>
            <div class="buttonhome buttonshadow" id="noodlen">
                Noodlen
            </div>
        <% end %>
    <% end %>

</div>

app/views/welcome/new.html.erb
<h1>Testpage - NEW</h1>

<%= form_for @testtask, url: {action: "create"} do |f| %>
    <p>name</p>
    <%= f.text_field :title %>
    <p>beschreibung</p>
    <%= f.text_field :text %>


    <%= f.submit "Create" %>
<% end %>