config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'
  get 'tasks/create'
  get 'tasks/select_date'
  get 'tasks/user_weight', :as => "user_weight"
  get 'tasks/select_user', :as => "select_user"
  get 'task/event' => "tasks#event", :as => "event"
  post 'task/comments/create' => "comments#create"
  post 'task/attachments/create' => "attachments#create"
  get 'attachments/show',  :as => "download"

  match "tasks/participate" => "tasks#participate", :via => :post
  match "tasks/create_date" => "tasks#create_date", :via => :patch, :as => "create_date"
  get "tasks/delete_date/:task_id" => "tasks#delete_date", :as => "delete_date"
  match "tasks/create_user_weight" => "tasks#create_user_weight", :via => :patch, :as => "create_user_weight"

  resources :tasks, :except => :show

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "account" => "sessions#account", :as => "account"
  get "help" => "welcome#show", :as => "help"

  get "addfriends" => "friendships#new", :as => "addfriends"

  resources :users do
    collection do
      post 'multiple_update'
    end
  end

  resources :sessions
  resources :friendships
  resources :responses

  root 'welcome#index'
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :user
    belongs_to :friend, :class_name => 'User'
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

    #show add Friends page
    def new
        @myfriendships = Friendship.where(:user_id => current_user.id)
        possiblefriends = User.all
        users = Array.new
        possiblefriends.each do |user|
            if not @myfriendships.exists?(:friend_id => user.id)
                users.append(user)
            end
        end
        @users = users
        suggestions = Array.new
        possiblesuggestion = User.all
        possiblesuggestion.each do |suggestion|
            if suggestion.id != current_user.id && !@myfriendships.exists?(:friend_id => suggestion.id)
                suggestions.append(suggestion)
            end
        end
        @suggestion = suggestions[0..8]
        render "addFriends"
    end

    #create new friendship
    def create
        @myfriendships = Friendship.where(:user_id => current_user.id)
        if not @myfriendships.exists?(:friend_id => params[:friend_id])
            @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
            if @friendship.save
                flash[:notice] = "Friend added"
                redirect_to addfriends_path
            else
                flash[:notice] = "Unable to add friend"
                render "addFriends"
            end
        else
            flash[:notice] = "You are already friends with this user"
            render "addFriends"
        end    
    end

    #destroy friendship with id: :id
    def destroy
        @friendship = current_user.friendships.find(params[:id])
        @friendship.destroy
        flash[:notice] = "Removed friendship"
        redirect_to account_path
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/addFriends.html.erb
<%= link_to account_path  do%>
  <i class="fa fa-arrow-left"></i>
<% end %>

<a id="showsuggestions" class="floatright">show suggestions</a>

<div class="inputform inputsearch" id="friendsearch">
  <%= form_tag users_path, :method => "get" do %>
    <%= text_field_tag :search, params[:search], :class => "inputform" %>
    <%= submit_tag "Search", :name => nil, :class => "buttoninput buttonshadow"%>
  <% end %>
</div>

<div id="asearch">
  <% if @searchresults != nil %>
    <% for result in @searchresults %>
      <%= link_to (result), :action => :show, :id => result.id do %>
        <div class="friend floatleft">
          <div class="avatar_small floatleft">
            <%= image_tag avatar_url(result, 50), :class => "avatar" %>
          </div>
          <div class="fname floatleft">
            <%= result.username %>
          </div>
          <div class="fcompany floatleft">
            <%= result.company %>
          </div>
          <div class="fadd">
            <%= link_to friendships_path(:friend_id => result), :method => :post do%>
              <i class="fa fa-plus"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="flashmsg">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
    </div>
  <% end %>
  <div class="suggestion">
    <% if @suggestion %>
      <div class="suggestions">
        <% for suggestion in @suggestion %>
          <%= link_to (suggestion), :action => :show, :id => suggestion.id do %>
              <div class="friend floatleft">
                <div class="avatar_small floatleft">
                  <%= image_tag avatar_url(suggestion, 50), :class => "avatar" %>
                </div>
                <div class="fname floatleft">
                  <%= suggestion.username %>
                </div>
                <div class="fcompany floatleft">
                  <%= suggestion.company %>
                </div>
                <div class="fadd">
                  <%= link_to friendships_path(:friend_id => suggestion), :method => :post do%>
                    <i class="fa fa-plus"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>