config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'
  get 'tasks/create'
  get 'tasks/select_date'
  get 'tasks/user_weight', :as => "user_weight"
  get 'tasks/select_user', :as => "select_user"
  get 'task/event' => "tasks#event", :as => "event"
  post 'task/comments/create' => "comments#create"
  post 'task/attachments/create' => "attachments#create"
  get 'attachments/show',  :as => "download"

  match "tasks/participate" => "tasks#participate", :via => :post
  match "tasks/create_date" => "tasks#create_date", :via => :patch, :as => "create_date"
  get "tasks/delete_date/:task_id" => "tasks#delete_date", :as => "delete_date"
  match "tasks/create_user_weight" => "tasks#create_user_weight", :via => :patch, :as => "create_user_weight"

  resources :tasks, :except => :show

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "account" => "sessions#account", :as => "account"
  get "help" => "welcome#show", :as => "help"

  get "addfriends" => "friendships#new", :as => "addfriends"

  resources :users do
    collection do
      post 'multiple_update'
    end
  end

  resources :sessions
  resources :friendships
  resources :responses

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Noodle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <div id="header_body">
            <div id="logo">
                <%= link_to image_tag("logo.png", id: "logo", height: 45), root_path %>
            </div>
            <div id="nav">
                <% if current_user %>
                    <div class="navelement" id="noodler">
                        <%= link_to "Help", help_path %>
                    </div>
                    <div class="navelement" id="noodler">
                        <%= link_to "Noodlen", new_task_path %>
                    </div>
                    <div class="navelement" id="account">
                        <% if Attendee.where(user_id: current_user.id, participate: true, answered: nil).pluck(:task_id).length > 0 then %>
                            <div class="notification">
                                    <%= Attendee.where(user_id: current_user.id, participate: true, answered: nil).pluck(:task_id).length %>
                            </div>
                        <% end %>
                        <%= link_to current_user.username, account_path %>
                    </div>
                    <div class="navelement" id="logout">
                        <%= link_to "Log out", logout_path %>
                    </div>
                <% end %>
            </div>
        </div>
    </header>
    <div id="container">
        <div id="content">
            <%= yield %>
        </div>
    </div>
    <footer>
        &copy; Code Ninjas Fribourg 2014
    </footer>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>